apply plugin: 'com.android.application'

dependencies {
    implementation project(":mapsforge-map-android")
    implementation project(":mapsforge-themes")
    implementation project(":mapsforge-poi-android")
    implementation 'androidx.annotation:annotation:1.10.0'
    implementation 'androidx.core:core:1.19.0'
    implementation 'androidx.fragment:fragment:1.8.9'
    androidTestImplementation 'com.jayway.android.robotium:robotium-solo:5.6.3'
}

android {
    namespace = 'org.mapsforge.samples.android'
    compileSdkVersion androidCompileSdk()

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        versionCode project.versionCode()
        versionName project.versionName()
        minSdkVersion androidMinSdk()
        targetSdkVersion androidTargetSdk()
        testApplicationId "org.mapsforge.samples.android.test"
        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            resources.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
        androidTest {
            java.srcDirs = ['src/androidTest']
        }
    }

    lint {
        abortOnError = false
    }
}
