LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_ARM_MODE	:= thumb
LOCAL_MODULE	:= sqlite3_jni

#	sqlite3secure.c is part of the wxSQLite3 package
SQLITE3_SOURCES := sqlite3_jni.c sqlite3secure.c

SQLITE3_INCLUDE_DIRS := -I.

#	These flags mimick that found in Android's source	
SQLITE3_ANDROID_ADDITIONAL_FLAGS := -DHAVE_USLEEP=1 \
	-DSQLITE_ENABLE_MEMORY_MANAGEMENT=1
	-DSQLITE_DEFAULT_AUTOVACUUM=1 \
	-DTEMP_STORE=3
	
SQLITE3_OPT_DEFINES := -DSQLITE_THREADSAFE=1 \
	-DSQLITE_DEFAULT_FILE_FORMAT=4 \
	-DSQLITE_OMIT_TCL_VARIABLE=1 \
	-DSQLITE_HAS_CODEC=1 \
	-DNDEBUG=1 \
	-DSQLITE_OMIT_LOAD_EXTENSION=1 \
	-DSQLITE3_ANDROID=1 \
	-DSQLITE_ENABLE_COLUMN_METADATA=1 \
	-DSQLITE_DEFAULT_FOREIGN_KEYS=1 \
	-DSQLITE_DEFAULT_JOURNAL_SIZE_LIMIT=1048576 \
	-DSQLITE_ENABLE_RTREE=1 \
	-DSQLITE_ENABLE_FTS3=1 \
	-DSQLITE_ENABLE_FTS3_PARENTHESIS=1

SQLITE3_OPT_DEFINES += -DCANT_PASS_VALIST_AS_CHARPTR=1
	
ifneq ($(TARGET_ARCH),arm)
# This line seems to be bugged for x86 targets
#LOCAL_LDLIBS += -lpthread -ldl
endif

ifneq ($(TARGET_SIMULATOR),true)
LOCAL_SHARED_LIBRARIES := libdl
endif	

LOCAL_CFLAGS := $(SQLITE3_INCLUDE_DIRS) \
	$(SQLITE3_OPT_DEFINES) \
	$(SQLITE3_ANDROID_ADDITIONAL_FLAGS)
	
LOCAL_SRC_FILES := $(SQLITE3_SOURCES)

include $(BUILD_SHARED_LIBRARY)
	
	
